### Initialize ellipsoids with DPD

In [1]:
import gsd, gsd.hoomd 
import hoomd
import mbuild as mb
import numpy as np
import scipy.stats
import unyt as u
import warnings
from flowermd.base import Pack,Lattice, Simulation,BaseHOOMDForcefield,Polymer
from flowermd.base.system import System
from flowermd.library import EllipsoidForcefield, EllipsoidChain
from flowermd.utils import get_target_box_number_density
from flowermd.utils.constraints import create_rigid_ellipsoid_chain
from scipy.spatial.distance import pdist
warnings.filterwarnings('ignore')

/Users/ericjankowski/miniforge3/envs/mupt-init/lib/python3.12/site-packages/gmso/core/element.py:10: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename


In [2]:
class EllipsoidChainRand(Polymer):
    def __init__(
        self,
        lengths,
        num_mols,
        lpar,
        bead_mass,
        bond_L=0.1,
        name="ellipsoid_chain",
    ):
        self.bead_mass = bead_mass
        self.lpar = lpar
        self.bond_L = bond_L
        self.bead_constituents_types = ["X", "A", "T", "T"]
        super(EllipsoidChainRand, self).__init__(
            lengths=lengths, num_mols=num_mols, name=name
        )

    def _build(self, length):
        bead = mb.Compound(name="ellipsoid")
        center = mb.Compound(pos=(0, 0, 0), name="X", mass=self.bead_mass / 4)
        head = mb.Compound(
            pos=(0, 0, self.lpar + (self.bond_L / 2)),
            name="A",
            mass=self.bead_mass / 4,
        )
        tether_head = mb.Compound(
            pos=(0, 0, self.lpar), name="T", mass=self.bead_mass / 4
        )
        tether_tail = mb.Compound(
            pos=(0, 0, -self.lpar), name="T", mass=self.bead_mass / 4
        )
        bead.add([center, head, tether_head, tether_tail])
        bead.add_bond([center, head])

        chain = mb.Compound()
        last_bead = None
        buffer = self.lpar + (self.bond_L / 2)
        density = 0.5
        N=50
        L = np.cbrt(N / density)
        for i in range(length):
            translate_by = np.random.uniform(low=-((L/2)-buffer), high=(L/2)-buffer, size=(3,))#adding random bead shift
            print(translate_by)
            this_bead = mb.clone(bead)
            this_bead.translate(by=translate_by)
            chain.add(this_bead)
            if last_bead:
                chain.add_bond([this_bead.children[0], last_bead.children[1]])
                chain.add_bond([this_bead.children[3], last_bead.children[2]])
            last_bead = this_bead
        chain.name = f"{self.name}_{length}mer"

        return chain

class DPD_FF(BaseHOOMDForcefield):
    def __init__(
        self,
        epsilon,
        lpar,
        lperp,
        A,
        gamma,
        kT,
        r_cut,
        angle_k=None,
        angle_theta0=None,
        bond_k=100,
        bond_r0=0.1,
    ):
        self.epsilon = epsilon
        self.lpar=lpar
        self.lperp=lperp
        self.gamma = gamma
        self.A = A
        self.kT = kT
        self.r_cut = r_cut
        self.angle_k = angle_k
        self.angle_theta0 = angle_theta0
        self.bond_k = bond_k
        self.bond_r0 = bond_r0
        hoomd_forces = self._create_forcefield()
        super(DPD_FF, self).__init__(hoomd_forces)

    def _create_forcefield(self):
        forces = []
        # Bonds
        bond = hoomd.md.bond.Harmonic()
        bond.params["T-T"] = dict(k=self.bond_k, r0=self.bond_r0)
        bond.params["A-X"] = dict(k=0, r0=0)
        forces.append(bond)
        # Angles
        if all([self.angle_k, self.angle_theta0]):
            angle = hoomd.md.angle.Harmonic()
            angle.params["X-A-X"] = dict(k=self.angle_k, t0=self.angle_theta0)
            angle.params["A-X-A"] = dict(k=0, t0=0)
            forces.append(angle)
        # DPD Pairs
        nlist = hoomd.md.nlist.Cell(buffer=0.40, exclusions=["body"])
        dpd = hoomd.md.pair.DPD(nlist=nlist,kT=self.kT,default_r_cut=self.r_cut)
        dpd.params[("X", "X")] = dict(A=self.A, gamma=self.gamma)
        # Add zero pairs
        for pair in [
            ("R", "R"),
            ("T", "T"),
            ("T", "R"),
            ("A", "A"),
            ("A", "X"),
            ("A", "T"),
            ("A", "R"),
            ("X", "R"),
            ("X", "T"),
        ]:
            dpd.params[pair] = dict(A=0,gamma=0.1)
            dpd.params[pair].r_cut = 0.0
        forces.append(dpd)
        return forces

#write new system class to skip pack and shrink step
class RandomSystem(System):
    def __init__(self, molecules, base_units=dict(), buffer=1.00):
        self.buffer = buffer
        super(RandomSystem, self).__init__(
            molecules=molecules, base_units=base_units
        )
    def _build_system(self):
        chain = self.all_molecules
        L = 5.85 #need to figure how to get this from molecules
        box = mb.Box(lengths=np.array([L] * 3) * self.buffer)
        comp = mb.Compound()
        comp.add(chain)
        comp.box = box
        return comp

In [3]:
# Initialize and write out an ellipsoid chain configuration without relying on Pack()
ellipsoid_chain = EllipsoidChainRand(lengths=10,num_mols=10,lpar=1.0,bead_mass=1.0)
ff = DPD_FF(epsilon=1.0,lpar=1.0,lperp=0.5,A=100,gamma=1.0,kT=2.0,r_cut=1.94,bond_k=100,bond_r0=1.0,angle_k=30,angle_theta0=1.9)
ff.hoomd_forces
system = RandomSystem(molecules=ellipsoid_chain)
system.to_gsd('test.gsd')
gsd_path=('ellipsoid-test.gsd')
rigid_frame, rigid = create_rigid_ellipsoid_chain(
    system.hoomd_snapshot,lpar=1.0,lperp=0.5
)
ellipsoid_sim = Simulation(
    initial_state=rigid_frame,
    forcefield=ff.hoomd_forces,
    constraint=rigid,
    dt=0.0003,
    gsd_write_freq=int(100),
    gsd_file_name='trajectory.gsd',
    log_write_freq=int(100),
    log_file_name='log.txt')

ellipsoid_sim.save_restart_gsd()
ellipsoid_sim.run_NVT(n_steps=1e4, kT=2.0, tau_kt=10*ellipsoid_sim.dt)
ellipsoid_sim.flush_writers()


[-1.10003703 -0.74948378  0.3893793 ]
[-0.48960698 -0.33694905 -0.06000819]
[-0.46644378  1.1046171   0.32637855]
[ 0.06497195 -0.22279335  0.50117617]
[-0.92910186 -0.73365502 -0.42819077]
[ 0.89466965 -0.08510517  1.04435428]
[-0.51704808  0.56213575  0.39675489]
[-0.39227719  0.17217245 -0.89500918]
[-0.9488299  -0.69923938  0.30944362]
[ 1.09627835  0.25520545 -0.67045189]
[1.01511773 0.90487125 0.54473978]
[0.50296437 1.24751633 0.98675918]
[-0.96665681  0.73879016  0.9230146 ]
[ 0.05967659 -0.72991599  0.70829782]
[ 0.64303148 -0.33940639  0.01488193]
[-1.25531386 -1.25952529 -0.98214437]
[ 0.97478814 -1.25075657  1.24836033]
[-0.27908042 -0.63442525  0.16339833]
[ 0.4156675  -0.08786104  0.52511834]
[ 0.36182963 -0.19507779  1.18293387]
[ 0.3996748  -1.23906232  0.06298599]
[ 1.06922094 -1.0800768  -0.71248851]
[ 0.429976    0.44761002 -0.61063732]
[-0.52094808 -0.57214314 -0.10143466]
[-0.02182735  0.66066701  1.06555031]
[-1.04032889  1.13715155 -1.0398324 ]
[ 1.24066906 -0.59

*Warning*: angle.harmonic: specified K <= 0
*Warning*: angle.harmonic: specified t_0 <= 0


Initializing simulation state from a gsd.hoomd.Frame.
Step 100 of 10000; TPS: 361.58; ETA: 0.5 minutes
Step 200 of 10000; TPS: 506.48; ETA: 0.3 minutes
Step 300 of 10000; TPS: 591.69; ETA: 0.3 minutes
Step 400 of 10000; TPS: 653.69; ETA: 0.2 minutes
Step 500 of 10000; TPS: 702.38; ETA: 0.2 minutes
Step 600 of 10000; TPS: 744.96; ETA: 0.2 minutes
Step 700 of 10000; TPS: 781.45; ETA: 0.2 minutes
Step 800 of 10000; TPS: 813.75; ETA: 0.2 minutes
Step 900 of 10000; TPS: 844.29; ETA: 0.2 minutes
Step 1000 of 10000; TPS: 872.72; ETA: 0.2 minutes
Step 1100 of 10000; TPS: 900.33; ETA: 0.2 minutes
Step 1200 of 10000; TPS: 927.28; ETA: 0.2 minutes
Step 1300 of 10000; TPS: 952.38; ETA: 0.2 minutes
Step 1400 of 10000; TPS: 976.27; ETA: 0.1 minutes
Step 1500 of 10000; TPS: 998.57; ETA: 0.1 minutes
Step 1600 of 10000; TPS: 1019.81; ETA: 0.1 minutes
Step 1700 of 10000; TPS: 1039.65; ETA: 0.1 minutes
Step 1800 of 10000; TPS: 1058.97; ETA: 0.1 minutes
Step 1900 of 10000; TPS: 1078.48; ETA: 0.1 minutes
S

In [ ]:
# Old initialization using Pack() which calls Packmol. 

ellipsoid_chain = EllipsoidChainRand(lengths=10,num_mols=2,lpar=1.0,bead_mass=1.0)
ff = DPD_FF(epsilon=1.0,lpar=1.0,lperp=0.5,A=100,gamma=1.0,kT=2.0,r_cut=5.0,bond_k=100,bond_r0=1.0,angle_k=30,angle_theta0=1.9)
ff.hoomd_forces
system = Pack(molecules=ellipsoid_chain, density=0.01*u.Unit("nm**-3"),packing_expand_factor=1,edge=0,overlap=0,use_pbc=False,fix_orientation=True)
system.to_gsd('system.gsd')
gsd_path=('ellipsoid-test.gsd')
rigid_frame, rigid = create_rigid_ellipsoid_chain(
    system.hoomd_snapshot,lpar=1.0,lperp=0.5
)
ellipsoid_sim = Simulation(
    initial_state=rigid_frame,
    forcefield=ff.hoomd_forces,
    constraint=rigid,
    dt=0.0003,
    gsd_write_freq=int(100),
    gsd_file_name='trajectory.gsd',
    log_write_freq=int(100),
    log_file_name='log.txt')

ellipsoid_sim.save_restart_gsd()
ellipsoid_sim.run_NVT(n_steps=1e4, kT=2.0, tau_kt=10*ellipsoid_sim.dt)
ellipsoid_sim.flush_writers()

#ff = EllipsoidForcefield(epsilon=1.0,lpar=1.0,lperp=0.5,r_cut=5.0,bond_k=100,bond_r0=0.1,angle_k=30,angle_theta0=1.9)
